version: 2.1
orbs:
  azure-cli: circleci/azure-cli@1.0.0
jobs:
  build:
    docker:
      - image: cimg/openjdk:17.0
    steps:
      - checkout
      - restore_cache:
          keys:
            - v1-dependencies-{{ checksum "build.gradle" }}
            - v1-dependencies-
      - run: gradle dependencies
      - save_cache:
          paths:
            - ~/.gradle
          key: v1-dependencies-{{ checksum "build.gradle" }}
      - run: gradle test
      - run: gradle bootJar
      - persist_to_workspace:
          root: ./build/libs
          paths:
            - "*.jar"
  deploy:
    executor: azure-cli/default
    steps:
      - attach_workspace:
          at: .
      - azure-cli/install
      - azure-cli/login-with-service-principal
      - run: az webapp deploy --resource-group cabana --name cabana-service --type jar --src-path cabana-service.jar --restart true
workflows:
  build:
    jobs:
      - build:
          filters:
            branches:
              only:
                - main
      - deploy:
          requires:
            - build
          context:
            - azure