version: 2.1
orbs:
  azure-cli: circleci/azure-cli@1.0.0
  gradle: circleci/gradle@2.2.0
jobs:
  test:
    executor: gradle/default
    steps:
      - checkout
      - gradle/with_cache:
          steps:
            - run: ./gradlew test
  build:
    executor: gradle/default
    steps:
      - checkout
      - gradle/with_cache:
          steps:
            - run: ./gradlew bootJar
      - persist_to_workspace:
          root: ./build/libs
          paths:
            - "*.jar"
  deploy:
    executor: azure-cli/default
    steps:
      - attach_workspace:
          at: .
      - azure-cli/install
      - azure-cli/login-with-service-principal
      - run: az webapp deploy --resource-group cabana --name cabana-service --type jar --src-path cabana-service.jar --restart true
workflows:
  test-build-deploy:
    jobs:
      - test:
          filters:
            branches:
              only:
                - main
      - build:
          requires:
            - test
      - deploy:
          requires:
            - build
          context:
            - azure