version: 2.1
jobs:
  build:
    docker:
      - image: cimg/openjdk:17.0
    steps:
      - checkout
      - restore_cache:
          keys:
            - v1-dependencies-{{ checksum "build.gradle" }}
            - v1-dependencies-
      - run: gradle dependencies
      - save_cache:
          paths:
            - ~/.gradle
          key: v1-dependencies-{{ checksum "build.gradle" }}
      - run: gradle test
      - run: gradle bootJar
      - save_workspace:
          root: ./build/libs
          paths:
            - "*.jar"
  deploy:
    executor: azure-cli/default
    steps:
      - attach_workspace:
          at: .
      - run: echo "Deploy!"
workflows:
  build:
    jobs:
      - build:
          filters:
            branches:
              only:
                - main
      - deploy:
          requires:
            - build